insert into admin(admin_id,name,password) values('A1','joe','asdfgh');
insert into subscriber(id,name,password) values('S1','joseph','qwerty');
insert into subscriber(id,name,password) values('S2','john','zxcvbn');
insert into subscriber(id,name,password) values('S3','kevin','qwerty');
insert into subscriber(id,name,password) values('S4','luke','qwerty');
insert into subscriber(id,name,password) values('S5','christy','qwerty');
insert into product(p_id,p_name,category) values('P1','Nike Alpharun','running shoes');
insert into product(p_id,p_name,category) values('P2','Adidas','sports shoes');
insert into product(p_id,p_name,category) values('P3','Reebok','casual shoes');
insert into product(p_id,p_name,category) values('P4','Woodland','formal shoes');
insert into product(p_id,p_name,category) values('P5','Peter England','formal shoes');
insert into product(p_id,p_name,category) values('P6','Action','casual shoes');
insert into report(r_id,date,product_p_id,subscriber_id) values('R1','07-11-2022','P1','S2');
insert into report(r_id,date,product_p_id,subscriber_id) values('R2','07-11-2022','P2','S1');
insert into report(r_id,date,product_p_id,subscriber_id) values('R3','07-11-2022','P3','S2');
insert into report(r_id,date,product_p_id,subscriber_id) values('R4','07-11-2022','P1','S4');
insert into report(r_id,date,product_p_id,subscriber_id) values('R5','08-11-2022','P1','S2');
insert into report(r_id,date,product_p_id,subscriber_id) values('R6','08-11-2022','P3','S2');
insert into report(r_id,date,product_p_id,subscriber_id) values('R7','03-11-2022','P1','S5');
insert into report(r_id,date,product_p_id,subscriber_id) values('R8','04-11-2022','P1','S2');
insert into report(r_id,date,product_p_id,subscriber_id) values('R9','04-11-2022','P3','S4');